on:
  push:
    tags:
      - 'v*'
    # branches:
    #   - master

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Get DN Version
        run: |
          source dn.sh
          echo "DN_VERSION=$DN_SCRIPT_VERSION" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.DN_VERSION }}
          release_name: v${{ env.DN_VERSION }}
          draft: true
          prerelease: false
      - name: Upload a Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dn.sh
          asset_name: dn.sh
          asset_content_type: text/plain
